### ISSUE TITLE
The problem of handsontable scrolling

### ISSUE THREAD

**Issue by babyWatchmen** [handsontable/react-handsontable#125] opened 2019-01-08 08:46 UTC
![image](https://user-images.githubusercontent.com/24561833/50819265-8b864280-1364-11e9-88e0-b700f88f8447.png)

The div and HotTable are included in the body, and the height of the div is higher than that of the body,Two HotTables are included in the div element, and the contents of the table can be scrolled inside HotTable1. But when I scroll the HotTable to the bottom, it affects the scroll of the div element, which is not allowed to scroll.What's the reason for this?

**Comment by AMBudnik** [comment] 2019-01-14 11:21
Hey @babyWatchmen 

the issue sounds pretty similar to this one https://github.com/handsontable/handsontable/issues/5212
Can you confirm?

**Comment by wojciechczerniak** [comment] 2019-02-28 09:58
Duplicate of #5212

**Closed by wojciechczerniak** 2019-02-28 09:58 UTC
Labels: Status: Answered
