### ISSUE TITLE
React Cell Renderer

### ISSUE THREAD

**Issue by nickleach** [handsontable/react-handsontable#21] opened 2017-07-06 18:11 UTC
Are there any plans in the pipeline to support rendering react components within cells? For instance:
```
this.handsontableData = [
      ["", "Ford", "Volvo", "Toyota", "Action"],
      ["2016", 10, 11, 12, (<i className="fa fa-eye" onClick={() => console.log('clicked')}></i>)],
      ["2017", 20, 11, 14, (<i className="fa fa-eye" onClick={() => console.log('clicked')}></i>)],
      ["2018", 30, 15, 12, (<i className="fa fa-eye" onClick={() => console.log('clicked')}></i>)]
    ];
```

**Comment by wtfdaemon** [comment] 2017-07-27 00:12
We'd love to have this feature.

**Comment by zekedroid** [comment] 2017-10-09 23:44
I just posted this article explaining exactly how to do it! It's actually easy to do without by just rendering into the `td`s with ReactDOM.render, but you shouldn't do that because it'll create a memory leak.

https://medium.com/@zekeschmois/rendering-react-elements-into-infinite-scrollable-tables-using-least-recently-used-lru-cache-23d6a8624d45

I just made the library (react-lru) but it's so simple to use that it should be safe!

**Comment by AMBudnik** [comment] 2017-10-10 07:18
Thanks for sharing @zekedroid 
Looks pretty impressive

**Comment by zekedroid** [comment] 2017-10-10 13:40
And here's a codepen for those looking for a demo:

https://codepen.io/anon/pen/zEjLob?editors=0010

**Comment by aaronbeall** [comment] 2017-11-30 05:20
This would be very useful to have. The React wrapper is pretty spartan compared to say, ag-grid's React API.

**Comment by redbmk** [comment] 2019-04-15 19:37
Has anyone gotten `autoColumnSize` to work when rendering cells with React?

**Comment by wojciechczerniak** [comment] 2019-08-02 18:52
We will implement this within #130. It's already in progress and will be similar to Vue implementation that was released recently: https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-vue-hot-column.html

I'm closing this issue as a duplicate of #130

> Has anyone gotten `autoColumnSize` to work when rendering cells with React?

The calculator will need all HTML and styles rendered to get it correctly. May be hard to accomplish with dynamic components if not impossible.

**Closed by wojciechczerniak** 2019-08-02 18:52 UTC
Labels: Type: Improvement suggestion
