### ISSUE TITLE
More React friendly

### ISSUE THREAD

**Issue by kevinkam** [handsontable/react-handsontable#140] opened 2019-10-16 07:58 UTC
### Description
This package seems like just a wrapper for the core handsontable, it should be more react friendly.
Like `custom renderer`, it should be able to accept React component instead of just passing a HTML Element.

### Steps to reproduce
no need to reproduce

### Demo
no need demo

### Your environment
* React wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment] 2019-10-16 09:41
Hi. Thanks for taking the time to create this feature request. Good news is that it's already in progress as a part of #130,

Closing as a duplicate of #130

**Closed by wojciechczerniak** 2019-10-16 09:41 UTC
