### ISSUE TITLE
Webpack Minification/name mangling issue in BaseEditorComponent

### ISSUE THREAD

**Issue by JanVanRyswyck** [handsontable/react-handsontable#152] opened 2019-12-18 15:06 UTC
### Description
In a React application, we're using HandsonTable 7.2.2 together with HandsonTable 3.1.1 . In this application we have  a large table with several custom editors. These custom editors are all derived from BaseEditorComponent. Columns are defined like so:

```
<HotColumn title={title} data='someProperty' type='text'>
      <CustomRenderer1 hot-renderer />
      <CustomEditor1 hot-editor/>
</HotColumn>
<HotColumn title={otherTitle} data='otherProperty' type='text'>
      <CustomRenderer2 hot-renderer />
      <CustomEditor2 hot-editor/>
</HotColumn>
```

We're using Webpack 4.23.1 for building this front-end application. Everything works just fine as long as we build using `mode: development`. But when we use `mode: production`, the first custom editor (e.g. CustomEditor1) is used for all the other columns instead of their designated custom editor types.

I think I might have found the cause of this issue. It seems that it has something to do with the `this.constructor.name` on [this line](https://github.com/handsontable/react-handsontable/blob/master/src/baseEditorComponent.tsx#L22) in the constructor of the BaseEditorComponent. When I log the value of this name property after having built in `development` mode, it just outputs the name of every custom editor component (e.g. CustomEditor1, CustomEditor2, etc. ...). When I do the same after having built in `production` mode, it always outputs the value `t` for example, regardless of the defined custom editor component. 

Reading the code of the `emitEditorInstance`, I noticed that this editor name is being used in an editor cache. When it always has the value `t`, the cache will only ever have an instance of the custom editor for the first column that it encounters. 

Digging a little further, I found that using `constructor.name` isn't a very good idea when using WebPack (see [this post](https://stackoverflow.com/questions/49598260/webpacks-removes-classnames-when-minifying-uglifying-es6-code-with-inheritance) on StackOverflow).

Is it possible to provide a fix for this issue by no longer using `constructor.name`? Thanks in advance.

### Your environment
* React wrapper version: 3.1.1
* Handsontable version: 7.2.2
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment] 2019-12-20 10:40
Thank you for sharing. I've asked my colleague to investigate the case.

**Comment by AMBudnik** [comment] 2019-12-20 12:56
Will it be possible to send over the application code, @JanVanRyswyck ? We're investigating the case but missing logic for `CustomRenderer1` and and `CustomEditor1` is not helping.

**Comment by JanVanRyswyck** [comment] 2019-12-23 12:17
@AMBudnik This is proprietary code that I'm not able to publish in public. I'm not sure whether the implementations of the renderer/editor matters that much? If you really need these specific implementations, then I'll have to check and ask my client. 

What I can say is that both the renderer as well as the editor render/display a plain React component that is being used on forms throughout the application.

**Comment by AMBudnik** [comment] 2019-12-23 13:56
We do not have any developers on duty right now but we should recheck this after holidays.

**Comment by JanVanRyswyck** [comment] 2019-12-23 14:11
Sure thing. Do let me know if I can help by providing information.

**Comment by AMBudnik** [comment] 2020-01-13 10:13
We already chatted about the subject on emails, but as I did not get any update after the 8th of January I just wanted to ask if there's a possibility for you @JanVanRyswyck to send over the `package.json` file?

**Comment by JanVanRyswyck** [comment] 2020-01-13 12:31
@AMBudnik I can send you the necessary file. Can you provide me with an e-mail address where to send it?

**Comment by AMBudnik** [comment] 2020-01-13 13:43
@JanVanRyswyck please send it to support@handsontable.com

**Comment by JanVanRyswyck** [comment] 2020-01-13 13:59
@AMBudnik Done.

**Comment by AMBudnik** [comment] 2020-01-16 06:40
Hey @JanVanRyswyck 

we've built a new project and 

> the first custom editor is used for all the other columns instead of their designated custom editor types.

seem to be true. We're still investigating the case but I guess that I can attach the `bug` label.

**Comment by JanVanRyswyck** [comment] 2020-01-16 07:31
@AMBudnik As mentioned in the issue, it seems that it has something to do with the this.constructor.name on [this line](https://github.com/handsontable/react-handsontable/blob/master/src/baseEditorComponent.tsx#L22) in the constructor of the BaseEditorComponent.

**Comment by mcastro84** [comment] 2020-04-06 09:33
I'm having the same issue in production and this PR seems to fix it, thanks!
I've noticed that after editing a cell, if the next cell is a custom editor, pressing Enter will not open the custom editor.

This error is displayed in the console:
`index.js:1472 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

This seems to have been introduced with this PR as this was working before.

The version where it works: 3.1.2
The version where it doesn't work: current PR

If I can provide any more details, please just let me know.

Thanks

**Comment by jansiegel** [comment] 2020-04-06 09:59
@mcastro84 I'll take a look at this before merging this PR, thanks for reporting!

**Comment by jansiegel** [comment] 2020-04-06 14:26
@mcastro84 Do you think you could prepare a demo of this issue? I'm having problems reproducing it on my local setup.

You can use this Codesandbox template as a base: https://codesandbox.io/s/declaring-a-custom-editor-as-a-component-9cloj. It has this PR's build already preloaded.

**Comment by AMBudnik** [comment] 2020-04-07 06:33
It seems to be a known case https://www.debuggr.io/react-update-unmounted-component/

**Comment by mcastro84** [comment] 2020-04-07 08:16
@jansiegel Thanks for your quick reply, I'll try to prepare a demo today

**Comment by mcastro84** [comment] 2020-04-08 16:15
@AMBudnik Just a heads up, I did a quick test with your demo and couldn't replicate the issue. It might have something to do with my implementation as I'm updating Formik state with the data changes and feeding it back to the HotTable.

I guess somewhere in between, the Custom Editor is not mounted when I try to open it.
As a temporary fix, I've changed the "enterMoves" property to disable moving to the next cell and that will do for now.

Again, thank you for the fix to the minification issue

**Comment by jansiegel** [comment] 2020-04-09 09:02
@mcastro84 Sure! If you manage to pinpoint the issue and it will be caused by the wrapper, just let us know (maybe create a separate issue?).

**Comment by aninde** [comment] 2020-04-15 10:06
In the latest version of `Handsontable-react`, it is possible to use several custom editors. Demo made during tests https://jsfiddle.net/aninde/3tyk9a5c/2/ `Handsontable-React 3.1.3`, `Handsontable 7.4.0`

**Comment by AMBudnik** [comment] 2020-04-15 13:28
Hi @JanVanRyswyck @mcastro84  

[Handsontable for React 3.1.3](https://github.com/handsontable/react-handsontable/releases/tag/3.1.3) has just been published. Thank you for your input.

**Closed by AMBudnik** 2020-04-15 13:28 UTC
Labels: Breaking change, Type: Bug
